x = 940;
y = 700;
maxYvel = 12;
maxXvel = 12;
xVel = 0;
yVel = 0;
xAcc = 0;
yAcc = 0;
Thrust = 0.05;
numMissles = 5; //missles remaining
missleCapacity = 5; //missle capacity before reloading
canShoot = true;
reload = false;
runningTest = false;
testAcceleration = false;
testDone = false;