maxYvel = 12;
maxXvel = 12;
xVel = 0;
yVel = 0;
xAcc = 0;
yAcc = 0;
Thrust = 0.05;
numMissles = 5; //missles remaining
missleCapacity = 5; //missle capacity before reloading
canShoot = true;
reload = false;
numTestLoops = 0; //used to run test twice. Once for each direction
testMode = false;
runningTest = false;